DROP TABLE FW_DOC_CATALOG;
DROP TABLE FW_CODE;
DROP TABLE FW_CODE_TYPE;
DROP TABLE FW_PARAMETER;
DROP TABLE FW_LOG;

DROP TABLE FW_ROLE_AUTHORIZATION;
DROP TABLE FW_USER_AUTHORIZATION;
DROP TABLE FW_MENU;
DROP TABLE FW_ROLE;
DROP TABLE FW_USER;
DROP TABLE FW_GROUP;
