INSERT INTO [HS_CODE_TYPE] VALUES ('BLL_STA', 21, 'BLL_STA', '账单状态', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('CHG_TYP', 13, 'CHG_TYP', '记账类别', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('CRC_TYP', 15, 'CRC_TYP', '货币种类', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('CST_STA', 22, 'CST_STA', '客户状态', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('EIL_STA', 3, 'EIL_STA', '企业违规状态', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('EIL_TYP', 2, 'EIL_TYP', '企业违规类别', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('ENT_STA', 1, 'ENT_STA', '企业状态', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('FVR_MOD', 17, 'FVR_MOD', '优惠方式', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('FVR_STA', 18, 'FVR_STA', '优惠状态', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('LCS_TYP', 8, 'LCS_TYP', '工作认证', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('MER_RST', 9, 'MER_RST', '体检结果', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('MSR_UNT', 14, 'MSR_UNT', '计量单位', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('ODR_STA', 19, 'ODR_STA', '订单状态', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('PRS_TYP', 7, 'PRS_TYP', '亲友关系', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('RAT_STA', 16, 'RAT_STA', '价格状态', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('SVS_STA', 12, 'SVS_STA', '产品状态', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('WIL_STA', 11, 'WIL_STA', '人员违规状态', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('WIL_TYP', 10, 'WIL_TYP', '人员违规类别', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('WKR_LAN', 6, 'WKR_LAN', '工作语言', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('WKR_SKL', 5, 'WKR_SKL', '工作技能', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('WKR_STA', 4, 'WKR_STA', '人员状态', '');
GO
INSERT INTO [HS_CODE_TYPE] VALUES ('WST_STA', 20, 'WST_STA', '工单状态', '');
GO
