INSERT INTO [HS_CODE] VALUES ('BLL_STA_0', 'BLL_STA', '000', '0', '失效', '');
GO
INSERT INTO [HS_CODE] VALUES ('BLL_STA_1', 'BLL_STA', '001', '1', '正常', '');
GO
INSERT INTO [HS_CODE] VALUES ('CHG_TYP_00', 'CHG_TYP', '000', '00', '次', '');
GO
INSERT INTO [HS_CODE] VALUES ('CHG_TYP_01', 'CHG_TYP', '001', '01', '月', '');
GO
INSERT INTO [HS_CODE] VALUES ('CRC_TYP_000', 'CRC_TYP', '000', '000', '人民币元', '');
GO
INSERT INTO [HS_CODE] VALUES ('CRC_TYP_001', 'CRC_TYP', '001', '001', '美元', '');
GO
INSERT INTO [HS_CODE] VALUES ('CST_STA_0', 'CST_STA', '000', '0', '失效', '');
GO
INSERT INTO [HS_CODE] VALUES ('CST_STA_1', 'CST_STA', '001', '1', '正常', '');
GO
INSERT INTO [HS_CODE] VALUES ('EIL_STA_00', 'EIL_STA', '000', '00', '结案', '');
GO
INSERT INTO [HS_CODE] VALUES ('EIL_TYP_00', 'EIL_TYP', '000', '00', '欠薪', '');
GO
INSERT INTO [HS_CODE] VALUES ('ENT_STA_0', 'ENT_STA', '000', '0', '失效', '');
GO
INSERT INTO [HS_CODE] VALUES ('ENT_STA_1', 'ENT_STA', '001', '1', '正常', '');
GO
INSERT INTO [HS_CODE] VALUES ('FVR_MOD_00', 'FVR_MOD', '000', '00', '满减', '');
GO
INSERT INTO [HS_CODE] VALUES ('FVR_MOD_01', 'FVR_MOD', '001', '01', '满折', '');
GO
INSERT INTO [HS_CODE] VALUES ('FVR_MOD_02', 'FVR_MOD', '002', '02', '满送积分', '');
GO
INSERT INTO [HS_CODE] VALUES ('FVR_MOD_03', 'FVR_MOD', '003', '03', '客户级别减', '');
GO
INSERT INTO [HS_CODE] VALUES ('FVR_MOD_04', 'FVR_MOD', '004', '04', '客户级别折', '');
GO
INSERT INTO [HS_CODE] VALUES ('FVR_MOD_05', 'FVR_MOD', '005', '05', '用卷', '');
GO
INSERT INTO [HS_CODE] VALUES ('FVR_STA_0', 'FVR_STA', '000', '0', '失效', '');
GO
INSERT INTO [HS_CODE] VALUES ('FVR_STA_1', 'FVR_STA', '001', '1', '正常', '');
GO
INSERT INTO [HS_CODE] VALUES ('LCS_TYP_00', 'LCS_TYP', '000', '00', '家政服务上岗证', '');
GO
INSERT INTO [HS_CODE] VALUES ('MER_RST_00', 'MER_RST', '000', '00', '合格', '');
GO
INSERT INTO [HS_CODE] VALUES ('MER_RST_01', 'MER_RST', '001', '01', '不合格', '');
GO
INSERT INTO [HS_CODE] VALUES ('MSR_UNT_00', 'MSR_UNT', '000', '00', '次', '');
GO
INSERT INTO [HS_CODE] VALUES ('MSR_UNT_0000', 'MSR_UNT', '000000', '0000', '人*次', '');
GO
INSERT INTO [HS_CODE] VALUES ('MSR_UNT_01', 'MSR_UNT', '001', '01', '小时', '');
GO
INSERT INTO [HS_CODE] VALUES ('MSR_UNT_0100', 'MSR_UNT', '001000', '0100', '人*小时', '');
GO
INSERT INTO [HS_CODE] VALUES ('MSR_UNT_02', 'MSR_UNT', '002', '02', '周', '');
GO
INSERT INTO [HS_CODE] VALUES ('MSR_UNT_0200', 'MSR_UNT', '002000', '0200', '人*周', '');
GO
INSERT INTO [HS_CODE] VALUES ('MSR_UNT_03', 'MSR_UNT', '003', '03', '月', '');
GO
INSERT INTO [HS_CODE] VALUES ('MSR_UNT_0300', 'MSR_UNT', '003000', '0300', '人*月', '');
GO
INSERT INTO [HS_CODE] VALUES ('ODR_STA_0', 'ODR_STA', '000', '0', '失效', '');
GO
INSERT INTO [HS_CODE] VALUES ('ODR_STA_1', 'ODR_STA', '001', '1', '正常', '');
GO
INSERT INTO [HS_CODE] VALUES ('PRS_TYP_00', 'PRS_TYP', '000', '00', '父亲', '');
GO
INSERT INTO [HS_CODE] VALUES ('PRS_TYP_01', 'PRS_TYP', '001', '01', '母亲', '');
GO
INSERT INTO [HS_CODE] VALUES ('PRS_TYP_02', 'PRS_TYP', '002', '02', '儿子', '');
GO
INSERT INTO [HS_CODE] VALUES ('PRS_TYP_03', 'PRS_TYP', '003', '03', '女儿', '');
GO
INSERT INTO [HS_CODE] VALUES ('PRS_TYP_04', 'PRS_TYP', '004', '04', '哥哥', '');
GO
INSERT INTO [HS_CODE] VALUES ('PRS_TYP_05', 'PRS_TYP', '005', '05', '姐姐', '');
GO
INSERT INTO [HS_CODE] VALUES ('PRS_TYP_06', 'PRS_TYP', '006', '06', '弟弟', '');
GO
INSERT INTO [HS_CODE] VALUES ('PRS_TYP_07', 'PRS_TYP', '007', '07', '妹妹', '');
GO
INSERT INTO [HS_CODE] VALUES ('PRS_TYP_08', 'PRS_TYP', '008', '08', '叔伯辈', '');
GO
INSERT INTO [HS_CODE] VALUES ('PRS_TYP_09', 'PRS_TYP', '009', '09', '子侄辈', '');
GO
INSERT INTO [HS_CODE] VALUES ('PRS_TYP_10', 'PRS_TYP', '010', '10', '同辈堂表兄弟姐妹', '');
GO
INSERT INTO [HS_CODE] VALUES ('RAT_STA_0', 'RAT_STA', '000', '0', '失效', '');
GO
INSERT INTO [HS_CODE] VALUES ('RAT_STA_1', 'RAT_STA', '001', '1', '正常', '');
GO
INSERT INTO [HS_CODE] VALUES ('SVS_STA_0', 'SVS_STA', '000', '0', '失效', '');
GO
INSERT INTO [HS_CODE] VALUES ('SVS_STA_1', 'SVS_STA', '001', '1', '正常', '');
GO
INSERT INTO [HS_CODE] VALUES ('WIL_STA_00', 'WIL_STA', '000', '00', '结案', '');
GO
INSERT INTO [HS_CODE] VALUES ('WIL_TYP_00', 'WIL_TYP', '000', '00', '迟到', '');
GO
INSERT INTO [HS_CODE] VALUES ('WKR_LAN_00', 'WKR_LAN', '000', '00', '汉语', '');
GO
INSERT INTO [HS_CODE] VALUES ('WKR_LAN_0000', 'WKR_LAN', '000000', '0000', '汉语普通话', '');
GO
INSERT INTO [HS_CODE] VALUES ('WKR_LAN_0001', 'WKR_LAN', '000001', '0001', '汉语广东话', '');
GO
INSERT INTO [HS_CODE] VALUES ('WKR_SKL_00', 'WKR_SKL', '000', '00', '家庭保洁', '');
GO
INSERT INTO [HS_CODE] VALUES ('WKR_STA_0', 'WKR_STA', '000', '0', '失效', '');
GO
INSERT INTO [HS_CODE] VALUES ('WKR_STA_1', 'WKR_STA', '001', '1', '正常', '');
GO
INSERT INTO [HS_CODE] VALUES ('WST_STA_0', 'WST_STA', '000', '0', '失效', '');
GO
INSERT INTO [HS_CODE] VALUES ('WST_STA_1', 'WST_STA', '001', '1', '正常', '');
GO
